version: '3.8' 

services:
  postgres:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

    volumes:
      - PGDATA:/var/lib/postgresql/data

volumes:
  PGDATA:
    driver: local
